#!/usr/bin/env bash

POWER_SUPPLIES=/sys/class/power_supply

bat-status() {
  local BAT="$POWER_SUPPLIES/$1"

  local STATUS=$(cat "$BAT/status")
  local CAPACITY=$(cat "$BAT/capacity")
  local VOLTAGE=$(echo "scale=2; $(cat "$BAT/voltage_now") / 1000000" | bc)
  local VOLTAGE_CELL=$(echo "scale=2; $VOLTAGE / 3" | bc)

  echo "Battery:        $1"
  echo "Status is:      $STATUS"
  echo "Capacity is:    $CAPACITY"%
  echo "Voltage is:     $VOLTAGE"V
  echo "Voltage cell:   $VOLTAGE_CELL"V
}

if [ -d "$POWER_SUPPLIES/BAT0" ]; then
  bat-status BAT0
fi

if [ -d "$POWER_SUPPLIES/BAT1" ]; then
  echo ""
  bat-status BAT1
fi
