#!/usr/bin/env bash

if [ "$1" = "" ]; then
    echo "Directory not specified"
    exit 1
fi

directory="$1"

# Check if the directory exists
if [ -d "$directory" ]; then
    # Use find to locate all files in the directory
    find "$directory" -type f -print0 | while IFS= read -r -d $'\0' file; do
        echo -n "$(basename "$file"):"
        cat "$file" | head -n 1 | tr -d '\n'
        echo ""
    done
else
    echo "Directory not found: $directory"
    exit 1
fi
