#!/bin/bash

cwd=$(dirname "$0")

event=$1
mac=$2
ip=$3
hostname=$4

acl=/etc/hostapd/hostapd.accept


[ "$event" = "remove" ] && exit 0

push() {
    "$cwd/modules/pushover.sh/pushover.sh" -f /root/.config/pushover.conf "$1"
}

message="Client connected $mac $hostname Assigned IP $ip"
echo "$message"

grep "$mac" "$acl" || push "$message"

