#!/bin/bash

cwd=$(dirname "$0")

event=$1
mac=$2
ip=$3
hostname=$4

leases_file=/var/lib/dnsmasq/dnsmasq.leases


push() {
    "$cwd/modules/pushover.sh/pushover.sh" "$1"
}

echo "$event MAC: $mac IP: $ip hostname: $hostname"

[ "$event" != "add" ] && exit 0

message="Client connected $mac $hostname"

grep -qx "$mac" "$leases_file" || push "$message"

